---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-api-backend
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/sebi364/m169.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
